### PR TITLE
Update Citador

### LINKED ISSUE #135: [Bug] Message not cleared and placeholder sent after last Discord update
Since the latest Discord update (of today), there are two problems:
* The message sent is not cleared from the text box
* The placeholder "Message #general" is sent when the text box is empty.

Replacing `$('.textArea-2Spzkt').text()` by `$('.slateTextArea-1bp44y').text()` in both relevant places fixes the second problem, but I'm not sure how to fix the first one.

### LINKED ISSUE #139: Citador does not work per 22 Dec 2019
Today (22 Dec 2019) i received "downloading updates 3 of 3" when launching discord and after that citador no longer working.

Please investigate and update.

### PR DESCRIPTION
**Pull request by NightWolf1038**
Added new settings:
- Send quote before message (codeblocks only). Requested by #132 (I guess)
- Exclude details for Codeblocks.

image

Fixes:
- Issues with Slate text area (Fixes #135). Thanks to Marsonge and 1MaTo.
- Embeds are back and it's working again (Fixes #139).

### CODE REVIEW

**Comment by Mara-Li** [comment]
Hello, it's possible to have the file ? My citador doesn't work, and when I download the "plugin" on your fork, i have no option, and the quote just work with the quote blocks... The older version didn't work either :<

**Comment by NightWolf1038** [comment]
Yeah, here. Localization won't work because the new strings are not in the original localization file.
[Citador.zip](https://github.com/nirewen/Citador/files/3975727/Citador.zip)

**Comment by Mara-Li** [comment]
Thanks ! But I don't understand why citador doesn't ping (in Embed) the quoted people :<

**Comment by NightWolf1038** [comment]
That's a Discord thing I guess, I @ users in my bot's embeds and it won't ping them.

**Comment by NightWolf1038** [comment]
Update fixes #139

**Comment by marcussacana** [comment]
I modified here the send embed quote to allow put the message content after the quote,
I'm don't know the discord api to do something better, But you have any better hint?
I allways wanted put the embed before, i don't care for the small delay sending 2 messages :) 
```js
if(this.settings.quoteBeforeMessage == true) {
        let content = msgCnt.content.replace('﻿', '');
        this.MessageQueue.enqueue({
            type: "send",
            message: {
            channelId: cc.id,
            content: "",
            tts: false,
            nonce: message.id,
            embed
            }
        }, r => {
            r.ok ? (this.MessageController.receiveMessage(cc.id, r.body)) : (r.status >= 400 && r.status < 500 && r.body &&     this.MessageController.sendClydeError(cc.id, r.body.code),

            this.EventDispatcher.dispatch({
            type: this.MainDiscord.ActionTypes.MESSAGE_SEND_FAILED,
            messageId: msg.id,
            channelId: cc.id
            }));
        });
        this.MessageQueue.enqueue({
            type: "send",
            message: {
            channelId: cc.id,
            content: content, // Weird character when sending an empty message
            tts: false,
            nonce: this.SendMessage.createBotMessage(cc.id, msgCnt.content).id
            }
        }, r => {
            r.ok ? (this.MessageController.receiveMessage(cc.id, r.body)) : (r.status >= 400 && r.status < 500 && r.body &&     this.MessageController.sendClydeError(cc.id, r.body.code),
            this.EventDispatcher.dispatch({
            type: this.MainDiscord.ActionTypes.MESSAGE_SEND_FAILED,
            messageId: msg.id,
            channelId: cc.id
            }));
        });
      } else {
        this.MessageQueue.enqueue({

            type: "send",
            message: {
            channelId: cc.id,

            content: msgCnt.content.replace('﻿', ''), // Weird character when sending an empty message
            tts: false,
            nonce: message.id,
            embed

            }
        }, r => {
            r.ok ? (this.MessageController.receiveMessage(cc.id, r.body)) : (r.status >= 400 && r.status < 500 && r.body &&     this.MessageController.sendClydeError(cc.id, r.body.code),

            this.EventDispatcher.dispatch({
            type: this.MainDiscord.ActionTypes.MESSAGE_SEND_FAILED,
            messageId: msg.id,
            channelId: cc.id

            }));
        });
      }
```

**Comment by marcussacana** [comment]
ohh, and the settings menu is broken here... but i'm not sure if is because of my theme...

**Comment by NightWolf1038** [comment]
Afaik, you can't send the content after the embed if both are in the same message, so, the only way is sending two messages, embed first, then the content.
The quote before message option was intended to be only for quote blocks, I can include that maybe, if you want.

Also, don't use the file directly from my fork, I uploaded a release [here](https://github.com/NightWolf1038/Citador/releases/tag/1.10) where the settings are working properly, localization won't work since I'm using Nirewen's strings and the new strings are not in the original repo

**Comment by marcussacana** [comment]
Yeah, I think will be cool include to the embed quote, I really hated send the message before the quote at level I usually sent a empty message with the quote then write what I want comment.

About your fork have more than 1 month and isn't merged yet, the @nirewen is alive yet?

**Comment by marcussacana** [comment]
@LeventHAN Do you know why I get this error?
image
This error is triggered in this code: (In the return)
```js
  var MessageClasses = Object.assign({}, BdApi.findModuleByProps("containerCompact", "timestampCozy"), BdApi.findModuleByProps("messages"));
  var MessageSelectors = new Proxy(MessageClasses, {
    get: function (list, item) {
      return '.' + list[item].split(' ').filter(n => n.indexOf('da-') != 0).join('.');
    }
  });
```
I tested and looks like the `BdApi.findModuleByProps("containerCompact", "timestampCozy"),` is returning null

**Comment by marcussacana** [comment]
Nahh, Don't looks like a problem of the PR itself, just now the PR is outdated too... Looks like the @NightWolf1038 is MIA too?

**Comment by KimJiSung1** [comment]
Will this plugin ever come back?

**Comment by marcussacana** [comment]
Who know.

**Comment by NightWolf1038** [comment]
Closing this pull request since Discord added a Reply feature. I suggest all of you to use that instead of any version of Citador to avoid a ban to your account for breaking Discord's ToS. Feel free to use the code for educational purposes, I archived my fork in case anyone want to fork it to make a new version.

**Pull request closed without merging**
