### PR TITLE
Fix Citador after changes

### PR DESCRIPTION
**Pull request by CompletelyUnbelievable**
Download the fork [here](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/CompletelyUnbelievable/Citador/master/Citador.plugin.js).

The props for the guilds wrapper seem to have been changed causing the plugin to break. This should return it to working order.

### CODE REVIEW

**Comment by CompletelyUnbelievable** [comment]
Looking into the other issues stated in #115, seems as though I will have to change the get guilds function again among other things.

**Comment by CompletelyUnbelievable** [comment]
1. Changes in 78c2758
	- Fixes guild alignment issue pertaining to guilds without icons/avatars.
2. Changes in bdf6258
	- Commented out all the Zlib tooltips so it will stop spamming console with errors, iirc Zlib's ToolTips have been broken for a while so just un-comment them when they are fixed. Making new tooltips is an option.
	- Changed various things pertaining to how the guilds function works and how it is handled in places such as the settings panel. This also fixed the guild icons in the settings panel meaning the embeds should work now.
	- The way the settings panel generates the guilds has been changed and now has the ability use the animated guild icons.
3. Changes in 78478ae
	- Fixed a few non-issue typos.
4. Thoughts/tasks
	- In the issue it was stated that quoting images does not work, which is true but I have not seen anything that leads me to believe that it had that ability yet or in the past. If I get a chance I'll look into it more.
	- I had a small issue when quoting where the quote message box disappeared when going between guilds. Happened once and could not reproduce so it seems like a non-issue.
	- I'm do not think keeping the old guilds function would even work as an appropriate backup anymore. So I'll probably remove it when I go through the comments that I added.

**Comment by CompletelyUnbelievable** [comment]
1. Changes in 2cfcf55
	- For sending either quotes, removes blank newlines from the message content.
	- Added function _getMessageAttachments_ to return an array of message attachment urls.
	- For sending either quotes, adds any unused message attachments to the end of the message content.
	- Changed how the function _getIconTemplate_ handles a case where a guild's acronym cannot be found. 
	- Cleaned up comments and removed the old guilds function.

**Comment by Rhyme** [comment]
Just a heads up cross-guild/server quoting is busted (again) on the latest Discord update 6:00PM CST, was working fine before, the core quiting functionality is still fine

**Comment by CompletelyUnbelievable** [comment]
@Rhyme Cannot reproduce in my fork, and if there was an update then it was silent and so far has not caused any issues. My guess is that you hadn't closed-discord/checked-for-updates for a while and didn't get the update from 3-4 days ago (The issue referenced) until now. If you are using PTB/Canary, I am not focusing on those and I am just working on stable. Assuming you are on stable and are trying to use my fork, then you might want to make sure you restart discord before trying to use it b/c I'm pretty sure that Citador isn't removing things completely/properly when disabled.

**Comment by S-B99** [comment]
I can't send messages with this fork either. Attacted downloaded one in case I downloaded wrong one

Plugin
https://pastebin.com/mwxt0bsG

Config
https://pastebin.com/mtmvBB3R

**Comment by CompletelyUnbelievable** [comment]
@S-B99 That pastebin of the plugin is the same as the current fork, also nothing about the plugin file strikes me as an issue. Try reading what I said to Rhyme and try that, and **if you have not already downloaded/tried-redownloading Zere's plugin library then please try that as well (I'm making a point of this b/c I forgot to include it when replying to Rhyme).** If the issue persists then please state which version of discord you are on stable/canary/ptb and post the console error you are getting from citador and/or ZLibrary (Zere's Plugin Library). You can send it in a discord DM if you want. If I am lucky then I will be home later today to check and see if anything changed.

**Comment by S-B99** [comment]
Hi, I don't use zere's library and I'm on stable. I'll be home in about 3
hours to post logs.

**Comment by CompletelyUnbelievable** [comment]
@S-B99 Well Citador uses Zere's plugin library plugin regardless of if you have it, by loading a less updated version of it that can have bugs or issues separate from the plugin. So you should try downloading the plugin first to see if that solves the issue.

**Comment by S-B99** [comment]
Fixed with zere's library update

**Comment by Firecul** [comment]
Thank you, your code fixes the not posting bug I've been having also. Hopefully this is approved soon.

**Comment by shinji257** [comment]
I went and did a clean load and it seems to be working 100% for me as long as you are quoting others.  You can't quote yourself but then again I don't know if you could do so before either.  This includes across guilds.

> In the issue it was stated that quoting images does not work, which is true but I have not seen anything that leads me to believe that it had that ability yet or in the past. If I get a chance I'll look into it more. A way to do so would be to replace the image with the url upon posting it.

If you are using code blocks then images will not show up because code blocks can't include images (it's just supposed to be text).  This is also why emoji's just show up as what you would type in to get them otherwise.

Embedded quotes do support images and showing emoji's but because it can be considered self botting it can also get you banned so you don't really want to use that method anyways.

**Comment by CompletelyUnbelievable** [comment]
> I went and did a clean load and it seems to be working 100% for me as long as you are quoting others. You can't quote yourself but then again I don't know if you could do so before either. This includes across guilds.

You should be able to quote yourself, I did it multiple times while testing. Off the top of my head, I wouldn't know why you would be having that issue especially if you tried the answers that I provided to the others here.
> If you are using code blocks then images will not show up because code blocks can't include images (it's just supposed to be text). This is also why emoji's just show up as what you would type in to get them otherwise.

Yes that is intended behavior so that people understand that you are quoting someone else. In this fork I made it so that if you quote a message (embedded or not) that has an uploaded image attachment (In the case that it is not being used for an embedded quote) then it will add the link(s) to it at the end of the quote, It's not done that well b/c I have not gotten the chance to change it yet and I would have to change how the quote preview works somehow so that it properly conveys this. For right now adding the image attachment links is a hack job.

> Embedded quotes do support images and showing emoji's but because it can be considered self botting it can also get you banned so you don't really want to use that method anyways.

TBH I'm not sure what you are trying to convey with is part beyond the differences of the codeblock and embeded quotes. 
1. Thoughts/tasks
- Quoting does not check the message size, so you can quote a message of over 2,000 characters, have it fail to send, and have clyde tell you that you cannot message the "user" (This can happen in a text channel) due to not sharing a guild, are not friends, or having them blocked.

**Comment by WoodenArow** [comment]
thx

**Comment by nirewen** [comment]
@CompletelyUnbelievable Tell me when it's ready to merge, I see you're still adding changes so I didn't merge it yet, though everybody is saying it already works. Thanks for the fix in advance!

**Comment by CompletelyUnbelievable** [comment]
@nirewen Yea, I finished the fix a while ago and I've been adding other things besides the fix as I've been going along. If you want you can merge this and I can continue off of another pull request. Feel free to double check what else I've been changing before a merge.
1. Changes in 4873da8
- Created the function "getMessageContent" (a replacement for "getMessageAttachments") to grab the content of the message and any attachments at the same time allowing the image urls to appear in the same spot as the image would be. Currently only used for codeblock quotes.
- Added a check for when a codeblock quote is over 2000 characters and prevents it from being sent.
2. Thoughts/tasks
- BdApi's showToast is moved by the quote box making it appear off-screen so there is no convent way to notify the user. Might be able to set a timeout for it to display the toast later but that does not seem like the best idea.
- Test the limits of embeded quote character limits and then do the same as I've done for codeblocks here.

**Comment by CompletelyUnbelievable** [comment]
@nirewen Feel free to check/merge then I can move on to a new pull request for the other changes I was making. 3d038ea is just minor changes like removing useless comments that I thought about while checking to see if/when this would be merged.

**Pull request merged**
